name: bluez
version: 0.8.2

description:
  Provides a client to connect to BlueZ - the Linux Bluetooth stack.

homepage: https://github.com/canonical/bluez.dart

environment:
  sdk: '>=2.17.0 <4.0.0'

platforms:
  linux:

dependencies:
  dbus: 
    git:
      url: https://github.com/free-explorers/dbus.dart

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.8
  test_cov: ^1.0.1
